### ISSUE TITLE
Running scripts at subMIT

### ISSUE THREAD

**Issue by Sangbaek** [mit-mc-clas12/clas12simulations#45]
The current version of codes cannot run at my macOS local with following error messages:

`python src/Submit_Job.py
Traceback (most recent call last):
 File "src/Submit_Job.py", line 34, in <module>
   db_batch_entry.Batch_Entry(args.scard)
 File "/Users/sangbaek/CLAS12/clas12simulation/src/db_batch_entry.py", line 26, in Batch_Entry
   username = user_validation.user_validation()
 File "/Users/sangbaek/CLAS12/clas12simulation/src/utils/user_validation.py", line 19, in user_validation
   user_already_exists = utils.sql3_grab(strn)
 File "/Users/sangbaek/CLAS12/clas12simulation/src/utils/utils.py", line 79, in sql3_grab
   c.execute(strn)
sqlite3.OperationalError: no such column: hostname
`

and at subMIT
`
CLAS12 Off Campus Resources Database not found, creating!
Traceback (most recent call last):
 File "src/Submit_Job.py", line 31, in <module>
   create_database.create_database(args)
 File "/afs/lns.mit.edu/user/sangbaek/test/clas12simulations/src/utils/create_database.py", line 19, in create_database
   file_struct.PKs[i],file_struct.foreign_key_relations[i])
 File "/afs/lns.mit.edu/user/sangbaek/test/clas12simulations/src/utils/utils.py", line 57, in create_table
   sql3_exec(strn)
 File "/afs/lns.mit.edu/user/sangbaek/test/clas12simulations/src/utils/utils.py", line 66, in sql3_exec
   printer2('Executing SQL Command: {}'.format(strn)) #Turn this on for explict printing of all DB write commands
ValueError: zero length field name in format
`

**Comment by robertej-phd** [comment]
Hi Sangbaek,

For running on your local macOS, it looks like there is an existing SQLite database that is in an old format. I would try to make sure there is no existing database (it should be in clas12simulations/database/CLAS12_OCRDB.db if it exists - you can just use rm database/CLAS12_OCRDB.db if it exists). Then rerun src/Submit_Job.py, and a new database should be created, with the updated file structure. If problems persist, please comment below.

I tried to run at SubMIT and had the same error you found. I've actually had this in the past, its just been a while since I've tried to run on SubMIT. Basically in python versions < 2.7, you have to specify the position of arguments when using "format" in strings, i.e. you cant use {}, you have to use {0}, etc. I did not notice this error straight away because on my local I am using python v 2.7.15rc1.

If you try this code on ifarm it will work (I just tried it so I'm pretty confident of this). This is because ifarm uses Python 2.7.12. Note SubMIT uses 2.6.6. This is a great catch though and we need to go through the code and replace any empty {} calls with numbered brackets. I can do this on the next PR, or someone else can if they feel like it.

Again if you want to try it on ifarm the code to test and run should really just be:

git clone https://github.com/mit-mc-clas12/clas12simulations
cd clas12simulations
python2 src/Submit_Job.py

Please comment if this does not work

**Comment by Sangbaek** [comment]
This is very interesting. Yes, I checked your codes run well at jlab environment including scosg16.

**Comment by Sangbaek** [comment]
I removed database/CLAS12_OCRDB.db and witnessed codes ran well in my local too.

**Comment by robertej-phd** [comment]
Fixed {} issues so this works on python < 2.7. Please reopen if similar issue is observed, but appears to be fixed on code living on robertej/master. PR forthcoming
